name: Java Obfuscator Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: '17'
        cache: gradle

    - name: Grant execute permissions for gradlew
      run: chmod +x gradlew

    - name: Build with Gradle
      run: ./gradlew clean build --no-daemon

    - name: Run tests
      run: ./gradlew test --no-daemon

    - name: Package JAR
      run: ./gradlew assemble --no-daemon

    - name: Upload build artifact
      uses: actions/upload-artifact@v4
      with:
        name: obfuscator-jar
        path: build/libs/*.jar

    - name: Verify build
      run: |
        echo "Listing JAR files:"
        ls -l build/libs/
